[package]
name = "qsim"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.17.2"
num-complex = "0.4.6"
rand = "0.10.1"
tracing = { version = "0.1.44", optional = true }
tracing-chrome = { version = "0.7.2", optional = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"], optional = true }

[features]
trace = ["dep:tracing", "dep:tracing-subscriber", "dep:tracing-chrome"]
